#!/bin/bash
export PATH=/usr/local/bin:$PATH
SWIFT_LINT=$(which swiftlint)

echo "🛠 Running SwiftLint --fix..."
$SWIFT_LINT lint --fix --use-script-input-files --force-exclude

echo "🔍 Running SwiftLint --strict..."
$SWIFT_LINT lint --strict --use-script-input-files --force-exclude

echo "✅ SwiftLint passed."